import type { RailwayMap } from "./types";

const DEFAULT_STATION_FONT_FAMILY = '"Avenir Next", "Helvetica Neue", Arial, sans-serif';
const DEFAULT_STATION_FONT_WEIGHT = "600" as const;
const DEFAULT_STATION_FONT_SIZE = 14;

export const LINE_PRESETS = [
  { id: "C1", color: "#e11d48", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C2", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" as const },
  { id: "C3", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C4", color: "#f59e0b", strokeWidth: 10, strokeStyle: "dotted" as const },
  { id: "C5", color: "#7c3aed", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C6", color: "#0891b2", strokeWidth: 10, strokeStyle: "dashed" as const },
];

export const INITIAL_MAP: RailwayMap = {
  config: {
    stationKinds: [
      { id: "sk1", name: "Stop", shape: "circle", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT, fontSize: DEFAULT_STATION_FONT_SIZE },
      { id: "sk2", name: "Hub", shape: "interchange", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: "700", fontSize: 15 },
      { id: "sk3", name: "Terminal", shape: "terminal", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT, fontSize: DEFAULT_STATION_FONT_SIZE },
    ],
    lines: [
      { id: "l1", name: "C1", color: "#e11d48", strokeWidth: 10, strokeStyle: "solid" },
      { id: "l2", name: "C2", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" },
      { id: "l3", name: "C3", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" },
    ],
  },
  model: {
  sheets: [
    { id: "sh1", name: "Regional Overview" },
    { id: "sh2", name: "Urban Detail" },
  ],
  nodes: [
    { id: "n1", sheetId: "sh1", x: 170, y: 220 },
    { id: "n2", sheetId: "sh1", x: 340, y: 220 },
    { id: "n3", sheetId: "sh1", x: 510, y: 220 },
    { id: "n4", sheetId: "sh1", x: 680, y: 220 },
    { id: "n5", sheetId: "sh1", x: 340, y: 360 },
    { id: "n6", sheetId: "sh1", x: 510, y: 360 },
    { id: "n7", sheetId: "sh1", x: 510, y: 110 },
    { id: "n8", sheetId: "sh1", x: 680, y: 110 },
    { id: "n9", sheetId: "sh2", x: 200, y: 220 },
    { id: "n10", sheetId: "sh2", x: 320, y: 220 },
    { id: "n11", sheetId: "sh2", x: 440, y: 220 },
    { id: "n12", sheetId: "sh2", x: 560, y: 220 },
    { id: "n13", sheetId: "sh2", x: 320, y: 340 },
    { id: "n14", sheetId: "sh2", x: 440, y: 340 },
  ],
  stations: [
    { id: "s1", nodeId: "n1", name: "Westside", kindId: "sk3", label: { x: 170, y: 196, align: "top" } },
    { id: "s2", nodeId: "n2", name: "Central Park", kindId: "sk2", label: { x: 340, y: 196, align: "top" } },
    { id: "s3", nodeId: "n3", name: "Museum", kindId: "sk2", label: { x: 510, y: 196, align: "top" } },
    { id: "s4", nodeId: "n4", name: "Eastside", kindId: "sk3", label: { x: 680, y: 196, align: "top" } },
    { id: "s5", nodeId: "n5", name: "Harbor", kindId: "sk1", label: { x: 340, y: 386, align: "bottom" } },
    { id: "s6", nodeId: "n6", name: "Airport", kindId: "sk3", label: { x: 510, y: 386, align: "bottom" } },
    { id: "s7", nodeId: "n8", name: "North Hill", kindId: "sk3", label: { x: 680, y: 86, align: "top" } },
    { id: "s8", nodeId: "n9", name: "Inner West", kindId: "sk1", label: { x: 200, y: 196, align: "top" } },
    { id: "s9", nodeId: "n10", name: "Central", kindId: "sk2", label: { x: 320, y: 196, align: "top" } },
    { id: "s10", nodeId: "n11", name: "Market", kindId: "sk2", label: { x: 440, y: 196, align: "top" } },
    { id: "s11", nodeId: "n12", name: "East Gate", kindId: "sk3", label: { x: 560, y: 196, align: "top" } },
    { id: "s12", nodeId: "n13", name: "Docklands", kindId: "sk1", label: { x: 320, y: 366, align: "bottom" } },
    { id: "s13", nodeId: "n14", name: "Airport Spur", kindId: "sk3", label: { x: 440, y: 366, align: "bottom" } },
  ],
  segments: [
    { id: "sg1", sheetId: "sh1", fromNodeId: "n1", toNodeId: "n2", geometry: { kind: "straight" } },
    { id: "sg2", sheetId: "sh1", fromNodeId: "n2", toNodeId: "n3", geometry: { kind: "straight" } },
    { id: "sg3", sheetId: "sh1", fromNodeId: "n3", toNodeId: "n4", geometry: { kind: "straight" } },
    { id: "sg4", sheetId: "sh1", fromNodeId: "n2", toNodeId: "n5", geometry: { kind: "straight" } },
    { id: "sg5", sheetId: "sh1", fromNodeId: "n5", toNodeId: "n6", geometry: { kind: "straight" } },
    { id: "sg6", sheetId: "sh1", fromNodeId: "n3", toNodeId: "n7", geometry: { kind: "straight" } },
    { id: "sg7", sheetId: "sh1", fromNodeId: "n7", toNodeId: "n8", geometry: { kind: "straight" } },
    { id: "sg8", sheetId: "sh2", fromNodeId: "n9", toNodeId: "n10", geometry: { kind: "straight" } },
    { id: "sg9", sheetId: "sh2", fromNodeId: "n10", toNodeId: "n11", geometry: { kind: "straight" } },
    { id: "sg10", sheetId: "sh2", fromNodeId: "n11", toNodeId: "n12", geometry: { kind: "straight" } },
    { id: "sg11", sheetId: "sh2", fromNodeId: "n10", toNodeId: "n13", geometry: { kind: "straight" } },
    { id: "sg12", sheetId: "sh2", fromNodeId: "n13", toNodeId: "n14", geometry: { kind: "straight" } },
  ],
  lineRuns: [
    { id: "lr1", lineId: "l1", segmentIds: ["sg1", "sg2", "sg3"] },
    { id: "lr2", lineId: "l2", segmentIds: ["sg1", "sg2", "sg6", "sg7", "sg8", "sg9", "sg10"] },
    { id: "lr3", lineId: "l3", segmentIds: ["sg2", "sg4", "sg5", "sg9", "sg11", "sg12"] },
  ],
  },
};

export const DEVELOPMENT_BOOTSTRAP_MAP: RailwayMap = {
  config: {
    stationKinds: [
      { id: "sk-stop", name: "Stop", shape: "circle", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT, fontSize: DEFAULT_STATION_FONT_SIZE },
      { id: "sk-hub", name: "Hub", shape: "interchange", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: "700", fontSize: 15 },
      { id: "sk-terminal", name: "Terminal", shape: "terminal", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT, fontSize: DEFAULT_STATION_FONT_SIZE },
      { id: "sk-express", name: "Express Stop", shape: "circle", fontFamily: '"Gill Sans", "Avenir Next", sans-serif', fontWeight: "700", fontSize: 16 },
      { id: "sk-heritage", name: "Heritage", shape: "circle", fontFamily: '"Baskerville", "Times New Roman", serif', fontWeight: "500", fontSize: 15 },
    ],
    lines: [
      { id: "l-red", name: "Red", color: "#dc2626", strokeWidth: 10, strokeStyle: "solid" },
      { id: "l-blue", name: "Blue", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" },
      { id: "l-green", name: "Green", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" },
      { id: "l-gold", name: "Gold", color: "#d97706", strokeWidth: 8, strokeStyle: "dotted" },
      { id: "l-teal", name: "Teal", color: "#0f766e", strokeWidth: 12, strokeStyle: "solid" },
      { id: "l-violet", name: "Violet", color: "#7c3aed", strokeWidth: 8, strokeStyle: "dashed" },
      { id: "l-slate", name: "Night", color: "#334155", strokeWidth: 6, strokeStyle: "solid" },
    ],
  },
  model: {
    sheets: [
      { id: "sh-ov", name: "Regional Overview" },
      { id: "sh-west", name: "Western Corridor" },
      { id: "sh-core", name: "Central Core" },
      { id: "sh-harbor", name: "Harbor District" },
      { id: "sh-north", name: "Northern District" },
      { id: "sh-south", name: "Southern Arc" },
    ],
    nodes: [
      { id: "n-ov-1", sheetId: "sh-ov", x: 110, y: 260 },
      { id: "n-ov-2", sheetId: "sh-ov", x: 260, y: 260 },
      { id: "n-ov-3", sheetId: "sh-ov", x: 430, y: 260 },
      { id: "n-ov-4", sheetId: "sh-ov", x: 610, y: 260 },
      { id: "n-ov-5", sheetId: "sh-ov", x: 790, y: 260 },
      { id: "n-ov-6", sheetId: "sh-ov", x: 960, y: 260 },
      { id: "n-ov-7", sheetId: "sh-ov", x: 430, y: 110 },
      { id: "n-ov-8", sheetId: "sh-ov", x: 430, y: 400 },
      { id: "n-ov-9", sheetId: "sh-ov", x: 610, y: 120 },
      { id: "n-ov-10", sheetId: "sh-ov", x: 610, y: 400 },

      { id: "n-west-1", sheetId: "sh-west", x: 140, y: 210 },
      { id: "n-west-2", sheetId: "sh-west", x: 280, y: 210 },
      { id: "n-west-3", sheetId: "sh-west", x: 420, y: 210 },
      { id: "n-west-4", sheetId: "sh-west", x: 560, y: 210 },
      { id: "n-west-5", sheetId: "sh-west", x: 700, y: 210 },
      { id: "n-west-6", sheetId: "sh-west", x: 280, y: 340 },
      { id: "n-west-7", sheetId: "sh-west", x: 420, y: 340 },
      { id: "n-west-8", sheetId: "sh-west", x: 560, y: 340 },
      { id: "n-west-9", sheetId: "sh-west", x: 700, y: 340 },
      { id: "n-west-10", sheetId: "sh-west", x: 420, y: 90 },

      { id: "n-core-1", sheetId: "sh-core", x: 150, y: 220 },
      { id: "n-core-2", sheetId: "sh-core", x: 270, y: 220 },
      { id: "n-core-3", sheetId: "sh-core", x: 390, y: 220 },
      { id: "n-core-4", sheetId: "sh-core", x: 510, y: 220 },
      { id: "n-core-5", sheetId: "sh-core", x: 630, y: 220 },
      { id: "n-core-6", sheetId: "sh-core", x: 270, y: 340 },
      { id: "n-core-7", sheetId: "sh-core", x: 390, y: 340 },
      { id: "n-core-8", sheetId: "sh-core", x: 510, y: 340 },
      { id: "n-core-9", sheetId: "sh-core", x: 630, y: 340 },
      { id: "n-core-10", sheetId: "sh-core", x: 390, y: 100 },
      { id: "n-core-11", sheetId: "sh-core", x: 510, y: 100 },
      { id: "n-core-12", sheetId: "sh-core", x: 510, y: 460 },

      { id: "n-harbor-1", sheetId: "sh-harbor", x: 180, y: 180 },
      { id: "n-harbor-2", sheetId: "sh-harbor", x: 320, y: 180 },
      { id: "n-harbor-3", sheetId: "sh-harbor", x: 460, y: 180 },
      { id: "n-harbor-4", sheetId: "sh-harbor", x: 600, y: 180 },
      { id: "n-harbor-5", sheetId: "sh-harbor", x: 740, y: 180 },
      { id: "n-harbor-6", sheetId: "sh-harbor", x: 320, y: 320 },
      { id: "n-harbor-7", sheetId: "sh-harbor", x: 460, y: 320 },
      { id: "n-harbor-8", sheetId: "sh-harbor", x: 600, y: 320 },
      { id: "n-harbor-9", sheetId: "sh-harbor", x: 740, y: 320 },

      { id: "n-north-1", sheetId: "sh-north", x: 180, y: 180 },
      { id: "n-north-2", sheetId: "sh-north", x: 340, y: 180 },
      { id: "n-north-3", sheetId: "sh-north", x: 500, y: 180 },
      { id: "n-north-4", sheetId: "sh-north", x: 660, y: 180 },
      { id: "n-north-5", sheetId: "sh-north", x: 340, y: 320 },
      { id: "n-north-6", sheetId: "sh-north", x: 500, y: 320 },
      { id: "n-north-7", sheetId: "sh-north", x: 660, y: 320 },

      { id: "n-south-1", sheetId: "sh-south", x: 180, y: 250 },
      { id: "n-south-2", sheetId: "sh-south", x: 340, y: 250 },
      { id: "n-south-3", sheetId: "sh-south", x: 500, y: 250 },
      { id: "n-south-4", sheetId: "sh-south", x: 660, y: 250 },
      { id: "n-south-5", sheetId: "sh-south", x: 820, y: 250 },
      { id: "n-south-6", sheetId: "sh-south", x: 340, y: 390 },
      { id: "n-south-7", sheetId: "sh-south", x: 500, y: 390 },
      { id: "n-south-8", sheetId: "sh-south", x: 660, y: 390 },
    ],
    stations: [
      { id: "s-ov-1", nodeId: "n-ov-1", name: "West Terminal", kindId: "sk-terminal", label: { x: 92, y: 236, align: "top" } },
      { id: "s-ov-2", nodeId: "n-ov-2", name: "Cedar Vale", kindId: "sk-stop", label: { x: 246, y: 236, align: "top" } },
      { id: "s-ov-3", nodeId: "n-ov-3", name: "Central Exchange", kindId: "sk-hub", label: { x: 454, y: 248, align: "right" } },
      { id: "s-ov-4", nodeId: "n-ov-4", name: "Airport Junction", kindId: "sk-hub", label: { x: 634, y: 248, align: "right" } },
      { id: "s-ov-5", nodeId: "n-ov-5", name: "East Bay", kindId: "sk-terminal", label: { x: 814, y: 248, align: "right" } },
      { id: "s-ov-6", nodeId: "n-ov-6", name: "Coast Terminal", kindId: "sk-terminal", label: { x: 984, y: 248, align: "right" } },
      { id: "s-ov-7", nodeId: "n-ov-7", name: "North Ridge", kindId: "sk-terminal", label: { x: 454, y: 98, align: "right" } },
      { id: "s-ov-8", nodeId: "n-ov-8", name: "South Harbor", kindId: "sk-terminal", label: { x: 454, y: 424, align: "right" } },
      { id: "s-ov-9", nodeId: "n-ov-9", name: "Aero City", kindId: "sk-express", label: { x: 634, y: 108, align: "right" } },
      { id: "s-ov-10", nodeId: "n-ov-10", name: "Marina South", kindId: "sk-express", label: { x: 634, y: 424, align: "right" } },

      { id: "s-west-1", nodeId: "n-west-1", name: "Ashford", kindId: "sk-stop", label: { x: 140, y: 186, align: "top" } },
      { id: "s-west-2", nodeId: "n-west-2", name: "Canal West", kindId: "sk-stop", label: { x: 280, y: 186, align: "top" } },
      { id: "s-west-3", nodeId: "n-west-3", name: "Museum Gardens", kindId: "sk-heritage", label: { x: 444, y: 204, align: "right" } },
      { id: "s-west-4", nodeId: "n-west-4", name: "Grand Market", kindId: "sk-hub", label: { x: 584, y: 204, align: "right" } },
      { id: "s-west-5", nodeId: "n-west-5", name: "West Air Link", kindId: "sk-express", label: { x: 724, y: 204, align: "right" } },
      { id: "s-west-6", nodeId: "n-west-6", name: "Brickworks", kindId: "sk-stop", label: { x: 280, y: 366, align: "bottom" } },
      { id: "s-west-7", nodeId: "n-west-7", name: "Old Docks", kindId: "sk-heritage", label: { x: 444, y: 366, align: "bottom" } },
      { id: "s-west-8", nodeId: "n-west-8", name: "Harbor West", kindId: "sk-stop", label: { x: 584, y: 366, align: "bottom" } },
      { id: "s-west-9", nodeId: "n-west-9", name: "Pier Nine", kindId: "sk-terminal", label: { x: 724, y: 366, align: "bottom" } },
      { id: "s-west-10", nodeId: "n-west-10", name: "Observatory", kindId: "sk-express", label: { x: 444, y: 78, align: "top" } },

      { id: "s-core-1", nodeId: "n-core-1", name: "West End", kindId: "sk-stop", label: { x: 150, y: 196, align: "top" } },
      { id: "s-core-2", nodeId: "n-core-2", name: "Museum", kindId: "sk-stop", label: { x: 270, y: 196, align: "top" } },
      { id: "s-core-3", nodeId: "n-core-3", name: "Central", kindId: "sk-hub", label: { x: 414, y: 214, align: "right" } },
      { id: "s-core-4", nodeId: "n-core-4", name: "Riverfront", kindId: "sk-stop", label: { x: 534, y: 214, align: "right" } },
      { id: "s-core-5", nodeId: "n-core-5", name: "East Gate", kindId: "sk-terminal", label: { x: 654, y: 214, align: "right" } },
      { id: "s-core-6", nodeId: "n-core-6", name: "Old Town", kindId: "sk-heritage", label: { x: 294, y: 364, align: "bottom" } },
      { id: "s-core-7", nodeId: "n-core-7", name: "Civic Center", kindId: "sk-hub", label: { x: 414, y: 364, align: "bottom" } },
      { id: "s-core-8", nodeId: "n-core-8", name: "Arena", kindId: "sk-express", label: { x: 534, y: 364, align: "bottom" } },
      { id: "s-core-9", nodeId: "n-core-9", name: "South Exchange", kindId: "sk-hub", label: { x: 654, y: 364, align: "bottom" } },
      { id: "s-core-10", nodeId: "n-core-10", name: "Hill Quarter", kindId: "sk-stop", label: { x: 414, y: 88, align: "top" } },
      { id: "s-core-11", nodeId: "n-core-11", name: "North Gate", kindId: "sk-express", label: { x: 534, y: 88, align: "top" } },
      { id: "s-core-12", nodeId: "n-core-12", name: "Harbor South", kindId: "sk-terminal", label: { x: 534, y: 486, align: "bottom" } },

      { id: "s-harbor-1", nodeId: "n-harbor-1", name: "Dry Dock", kindId: "sk-stop", label: { x: 180, y: 156, align: "top" } },
      { id: "s-harbor-2", nodeId: "n-harbor-2", name: "Harbor Market", kindId: "sk-stop", label: { x: 320, y: 156, align: "top" } },
      { id: "s-harbor-3", nodeId: "n-harbor-3", name: "Ferry Hub", kindId: "sk-hub", label: { x: 484, y: 174, align: "right" } },
      { id: "s-harbor-4", nodeId: "n-harbor-4", name: "Container Yards", kindId: "sk-express", label: { x: 624, y: 174, align: "right" } },
      { id: "s-harbor-5", nodeId: "n-harbor-5", name: "Ocean Terminal", kindId: "sk-terminal", label: { x: 764, y: 174, align: "right" } },
      { id: "s-harbor-6", nodeId: "n-harbor-6", name: "Shipwrights", kindId: "sk-heritage", label: { x: 320, y: 346, align: "bottom" } },
      { id: "s-harbor-7", nodeId: "n-harbor-7", name: "Canal Lift", kindId: "sk-stop", label: { x: 484, y: 346, align: "bottom" } },
      { id: "s-harbor-8", nodeId: "n-harbor-8", name: "Wharf East", kindId: "sk-stop", label: { x: 624, y: 346, align: "bottom" } },
      { id: "s-harbor-9", nodeId: "n-harbor-9", name: "Pier South", kindId: "sk-terminal", label: { x: 764, y: 346, align: "bottom" } },

      { id: "s-north-1", nodeId: "n-north-1", name: "Pine", kindId: "sk-stop", label: { x: 180, y: 156, align: "top" } },
      { id: "s-north-2", nodeId: "n-north-2", name: "North Central", kindId: "sk-hub", label: { x: 364, y: 174, align: "right" } },
      { id: "s-north-3", nodeId: "n-north-3", name: "Summit", kindId: "sk-terminal", label: { x: 524, y: 174, align: "right" } },
      { id: "s-north-4", nodeId: "n-north-4", name: "High Moor", kindId: "sk-express", label: { x: 684, y: 174, align: "right" } },
      { id: "s-north-5", nodeId: "n-north-5", name: "Valley", kindId: "sk-stop", label: { x: 364, y: 344, align: "right" } },
      { id: "s-north-6", nodeId: "n-north-6", name: "University North", kindId: "sk-stop", label: { x: 524, y: 344, align: "right" } },
      { id: "s-north-7", nodeId: "n-north-7", name: "Ridge Park", kindId: "sk-stop", label: { x: 684, y: 344, align: "right" } },

      { id: "s-south-1", nodeId: "n-south-1", name: "Canal South", kindId: "sk-stop", label: { x: 180, y: 226, align: "top" } },
      { id: "s-south-2", nodeId: "n-south-2", name: "South Junction", kindId: "sk-hub", label: { x: 364, y: 244, align: "right" } },
      { id: "s-south-3", nodeId: "n-south-3", name: "Garden Works", kindId: "sk-stop", label: { x: 524, y: 244, align: "right" } },
      { id: "s-south-4", nodeId: "n-south-4", name: "Lakeshore", kindId: "sk-stop", label: { x: 684, y: 244, align: "right" } },
      { id: "s-south-5", nodeId: "n-south-5", name: "Southport", kindId: "sk-terminal", label: { x: 844, y: 244, align: "right" } },
      { id: "s-south-6", nodeId: "n-south-6", name: "Freight Belt", kindId: "sk-express", label: { x: 364, y: 416, align: "bottom" } },
      { id: "s-south-7", nodeId: "n-south-7", name: "Depot Square", kindId: "sk-stop", label: { x: 524, y: 416, align: "bottom" } },
      { id: "s-south-8", nodeId: "n-south-8", name: "Marsh End", kindId: "sk-heritage", label: { x: 684, y: 416, align: "bottom" } },

      { id: "s-free-1", nodeId: null, name: "Future Airport Terminal", kindId: "sk-terminal" },
      { id: "s-free-2", nodeId: null, name: "River Museum", kindId: "sk-heritage" },
      { id: "s-free-3", nodeId: null, name: "Expo Grounds", kindId: "sk-express" },
    ],
    segments: [
      { id: "sg-ov-1", sheetId: "sh-ov", fromNodeId: "n-ov-1", toNodeId: "n-ov-2", geometry: { kind: "straight" } },
      { id: "sg-ov-2", sheetId: "sh-ov", fromNodeId: "n-ov-2", toNodeId: "n-ov-3", geometry: { kind: "straight" } },
      { id: "sg-ov-3", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-4", geometry: { kind: "straight" } },
      { id: "sg-ov-4", sheetId: "sh-ov", fromNodeId: "n-ov-4", toNodeId: "n-ov-5", geometry: { kind: "straight" } },
      { id: "sg-ov-5", sheetId: "sh-ov", fromNodeId: "n-ov-5", toNodeId: "n-ov-6", geometry: { kind: "straight" } },
      { id: "sg-ov-6", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-7", geometry: { kind: "straight" } },
      { id: "sg-ov-7", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-8", geometry: { kind: "straight" } },
      { id: "sg-ov-8", sheetId: "sh-ov", fromNodeId: "n-ov-4", toNodeId: "n-ov-9", geometry: { kind: "straight" } },
      { id: "sg-ov-9", sheetId: "sh-ov", fromNodeId: "n-ov-4", toNodeId: "n-ov-10", geometry: { kind: "straight" } },

      { id: "sg-west-1", sheetId: "sh-west", fromNodeId: "n-west-1", toNodeId: "n-west-2", geometry: { kind: "straight" } },
      { id: "sg-west-2", sheetId: "sh-west", fromNodeId: "n-west-2", toNodeId: "n-west-3", geometry: { kind: "straight" } },
      { id: "sg-west-3", sheetId: "sh-west", fromNodeId: "n-west-3", toNodeId: "n-west-4", geometry: { kind: "straight" } },
      { id: "sg-west-4", sheetId: "sh-west", fromNodeId: "n-west-4", toNodeId: "n-west-5", geometry: { kind: "straight" } },
      { id: "sg-west-5", sheetId: "sh-west", fromNodeId: "n-west-2", toNodeId: "n-west-6", geometry: { kind: "straight" } },
      { id: "sg-west-6", sheetId: "sh-west", fromNodeId: "n-west-6", toNodeId: "n-west-7", geometry: { kind: "straight" } },
      { id: "sg-west-7", sheetId: "sh-west", fromNodeId: "n-west-7", toNodeId: "n-west-8", geometry: { kind: "straight" } },
      { id: "sg-west-8", sheetId: "sh-west", fromNodeId: "n-west-8", toNodeId: "n-west-9", geometry: { kind: "straight" } },
      { id: "sg-west-9", sheetId: "sh-west", fromNodeId: "n-west-3", toNodeId: "n-west-7", geometry: { kind: "straight" } },
      { id: "sg-west-10", sheetId: "sh-west", fromNodeId: "n-west-3", toNodeId: "n-west-10", geometry: { kind: "straight" } },

      { id: "sg-core-1", sheetId: "sh-core", fromNodeId: "n-core-1", toNodeId: "n-core-2", geometry: { kind: "straight" } },
      { id: "sg-core-2", sheetId: "sh-core", fromNodeId: "n-core-2", toNodeId: "n-core-3", geometry: { kind: "straight" } },
      { id: "sg-core-3", sheetId: "sh-core", fromNodeId: "n-core-3", toNodeId: "n-core-4", geometry: { kind: "straight" } },
      { id: "sg-core-4", sheetId: "sh-core", fromNodeId: "n-core-4", toNodeId: "n-core-5", geometry: { kind: "straight" } },
      { id: "sg-core-5", sheetId: "sh-core", fromNodeId: "n-core-2", toNodeId: "n-core-6", geometry: { kind: "straight" } },
      { id: "sg-core-6", sheetId: "sh-core", fromNodeId: "n-core-6", toNodeId: "n-core-7", geometry: { kind: "straight" } },
      { id: "sg-core-7", sheetId: "sh-core", fromNodeId: "n-core-7", toNodeId: "n-core-8", geometry: { kind: "straight" } },
      { id: "sg-core-8", sheetId: "sh-core", fromNodeId: "n-core-8", toNodeId: "n-core-9", geometry: { kind: "straight" } },
      { id: "sg-core-9", sheetId: "sh-core", fromNodeId: "n-core-3", toNodeId: "n-core-7", geometry: { kind: "straight" } },
      { id: "sg-core-10", sheetId: "sh-core", fromNodeId: "n-core-4", toNodeId: "n-core-8", geometry: { kind: "straight" } },
      { id: "sg-core-11", sheetId: "sh-core", fromNodeId: "n-core-3", toNodeId: "n-core-10", geometry: { kind: "straight" } },
      { id: "sg-core-12", sheetId: "sh-core", fromNodeId: "n-core-4", toNodeId: "n-core-11", geometry: { kind: "straight" } },
      { id: "sg-core-13", sheetId: "sh-core", fromNodeId: "n-core-8", toNodeId: "n-core-12", geometry: { kind: "straight" } },

      { id: "sg-harbor-1", sheetId: "sh-harbor", fromNodeId: "n-harbor-1", toNodeId: "n-harbor-2", geometry: { kind: "straight" } },
      { id: "sg-harbor-2", sheetId: "sh-harbor", fromNodeId: "n-harbor-2", toNodeId: "n-harbor-3", geometry: { kind: "straight" } },
      { id: "sg-harbor-3", sheetId: "sh-harbor", fromNodeId: "n-harbor-3", toNodeId: "n-harbor-4", geometry: { kind: "straight" } },
      { id: "sg-harbor-4", sheetId: "sh-harbor", fromNodeId: "n-harbor-4", toNodeId: "n-harbor-5", geometry: { kind: "straight" } },
      { id: "sg-harbor-5", sheetId: "sh-harbor", fromNodeId: "n-harbor-2", toNodeId: "n-harbor-6", geometry: { kind: "straight" } },
      { id: "sg-harbor-6", sheetId: "sh-harbor", fromNodeId: "n-harbor-6", toNodeId: "n-harbor-7", geometry: { kind: "straight" } },
      { id: "sg-harbor-7", sheetId: "sh-harbor", fromNodeId: "n-harbor-7", toNodeId: "n-harbor-8", geometry: { kind: "straight" } },
      { id: "sg-harbor-8", sheetId: "sh-harbor", fromNodeId: "n-harbor-8", toNodeId: "n-harbor-9", geometry: { kind: "straight" } },
      { id: "sg-harbor-9", sheetId: "sh-harbor", fromNodeId: "n-harbor-3", toNodeId: "n-harbor-7", geometry: { kind: "straight" } },
      { id: "sg-harbor-10", sheetId: "sh-harbor", fromNodeId: "n-harbor-4", toNodeId: "n-harbor-8", geometry: { kind: "straight" } },

      { id: "sg-north-1", sheetId: "sh-north", fromNodeId: "n-north-1", toNodeId: "n-north-2", geometry: { kind: "straight" } },
      { id: "sg-north-2", sheetId: "sh-north", fromNodeId: "n-north-2", toNodeId: "n-north-3", geometry: { kind: "straight" } },
      { id: "sg-north-3", sheetId: "sh-north", fromNodeId: "n-north-3", toNodeId: "n-north-4", geometry: { kind: "straight" } },
      { id: "sg-north-4", sheetId: "sh-north", fromNodeId: "n-north-2", toNodeId: "n-north-5", geometry: { kind: "straight" } },
      { id: "sg-north-5", sheetId: "sh-north", fromNodeId: "n-north-5", toNodeId: "n-north-6", geometry: { kind: "straight" } },
      { id: "sg-north-6", sheetId: "sh-north", fromNodeId: "n-north-6", toNodeId: "n-north-7", geometry: { kind: "straight" } },
      { id: "sg-north-7", sheetId: "sh-north", fromNodeId: "n-north-3", toNodeId: "n-north-6", geometry: { kind: "straight" } },

      { id: "sg-south-1", sheetId: "sh-south", fromNodeId: "n-south-1", toNodeId: "n-south-2", geometry: { kind: "straight" } },
      { id: "sg-south-2", sheetId: "sh-south", fromNodeId: "n-south-2", toNodeId: "n-south-3", geometry: { kind: "straight" } },
      { id: "sg-south-3", sheetId: "sh-south", fromNodeId: "n-south-3", toNodeId: "n-south-4", geometry: { kind: "straight" } },
      { id: "sg-south-4", sheetId: "sh-south", fromNodeId: "n-south-4", toNodeId: "n-south-5", geometry: { kind: "straight" } },
      { id: "sg-south-5", sheetId: "sh-south", fromNodeId: "n-south-2", toNodeId: "n-south-6", geometry: { kind: "straight" } },
      { id: "sg-south-6", sheetId: "sh-south", fromNodeId: "n-south-6", toNodeId: "n-south-7", geometry: { kind: "straight" } },
      { id: "sg-south-7", sheetId: "sh-south", fromNodeId: "n-south-7", toNodeId: "n-south-8", geometry: { kind: "straight" } },
      { id: "sg-south-8", sheetId: "sh-south", fromNodeId: "n-south-3", toNodeId: "n-south-7", geometry: { kind: "straight" } },
    ],
    lineRuns: [
      { id: "lr-red", lineId: "l-red", segmentIds: ["sg-ov-1", "sg-ov-2", "sg-ov-3", "sg-ov-4", "sg-ov-5", "sg-west-1", "sg-west-2", "sg-west-3", "sg-west-4", "sg-core-1", "sg-core-2", "sg-core-3", "sg-core-4", "sg-north-1", "sg-north-2", "sg-north-3"] },
      { id: "lr-blue", lineId: "l-blue", segmentIds: ["sg-ov-2", "sg-ov-6", "sg-west-2", "sg-west-10", "sg-core-2", "sg-core-11", "sg-north-2", "sg-north-7"] },
      { id: "lr-green", lineId: "l-green", segmentIds: ["sg-ov-2", "sg-ov-7", "sg-west-5", "sg-west-6", "sg-west-7", "sg-west-8", "sg-south-1", "sg-south-2", "sg-south-3", "sg-south-4"] },
      { id: "lr-gold", lineId: "l-gold", segmentIds: ["sg-ov-3", "sg-ov-8", "sg-core-3", "sg-core-12", "sg-harbor-3", "sg-harbor-4"] },
      { id: "lr-teal", lineId: "l-teal", segmentIds: ["sg-core-3", "sg-core-10", "sg-core-8", "sg-core-13", "sg-harbor-2", "sg-harbor-9", "sg-harbor-7", "sg-harbor-8"] },
      { id: "lr-violet", lineId: "l-violet", segmentIds: ["sg-west-3", "sg-west-9", "sg-core-3", "sg-core-9", "sg-south-3", "sg-south-8"] },
      { id: "lr-slate", lineId: "l-slate", segmentIds: ["sg-harbor-1", "sg-harbor-2", "sg-harbor-3", "sg-harbor-10", "sg-south-5", "sg-south-6", "sg-south-7"] },
    ],
  },
};
