import type { RailwayMap } from "./types";

const DEFAULT_STATION_FONT_FAMILY = '"Avenir Next", "Helvetica Neue", Arial, sans-serif';
const DEFAULT_STATION_FONT_WEIGHT = "600" as const;

export const LINE_PRESETS = [
  { id: "C1", color: "#e11d48", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C2", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" as const },
  { id: "C3", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C4", color: "#f59e0b", strokeWidth: 10, strokeStyle: "dotted" as const },
  { id: "C5", color: "#7c3aed", strokeWidth: 10, strokeStyle: "solid" as const },
  { id: "C6", color: "#0891b2", strokeWidth: 10, strokeStyle: "dashed" as const },
];

export const INITIAL_MAP: RailwayMap = {
  sheets: [
    { id: "sh1", name: "Regional Overview" },
    { id: "sh2", name: "Urban Detail" },
  ],
  nodes: [
    { id: "n1", sheetId: "sh1", x: 170, y: 220 },
    { id: "n2", sheetId: "sh1", x: 340, y: 220 },
    { id: "n3", sheetId: "sh1", x: 510, y: 220 },
    { id: "n4", sheetId: "sh1", x: 680, y: 220 },
    { id: "n5", sheetId: "sh1", x: 340, y: 360 },
    { id: "n6", sheetId: "sh1", x: 510, y: 360 },
    { id: "n7", sheetId: "sh1", x: 510, y: 110 },
    { id: "n8", sheetId: "sh1", x: 680, y: 110 },
    { id: "n9", sheetId: "sh2", x: 200, y: 220 },
    { id: "n10", sheetId: "sh2", x: 320, y: 220 },
    { id: "n11", sheetId: "sh2", x: 440, y: 220 },
    { id: "n12", sheetId: "sh2", x: 560, y: 220 },
    { id: "n13", sheetId: "sh2", x: 320, y: 340 },
    { id: "n14", sheetId: "sh2", x: 440, y: 340 },
  ],
  stationKinds: [
    { id: "sk1", name: "Stop", shape: "circle", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT },
    { id: "sk2", name: "Hub", shape: "interchange", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: "700" },
    { id: "sk3", name: "Terminal", shape: "terminal", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT },
  ],
  stations: [
    { id: "s1", nodeId: "n1", name: "Westside", kindId: "sk3", label: { x: 170, y: 196, align: "top" } },
    { id: "s2", nodeId: "n2", name: "Central Park", kindId: "sk2", label: { x: 340, y: 196, align: "top" } },
    { id: "s3", nodeId: "n3", name: "Museum", kindId: "sk2", label: { x: 510, y: 196, align: "top" } },
    { id: "s4", nodeId: "n4", name: "Eastside", kindId: "sk3", label: { x: 680, y: 196, align: "top" } },
    { id: "s5", nodeId: "n5", name: "Harbor", kindId: "sk1", label: { x: 340, y: 386, align: "bottom" } },
    { id: "s6", nodeId: "n6", name: "Airport", kindId: "sk3", label: { x: 510, y: 386, align: "bottom" } },
    { id: "s7", nodeId: "n8", name: "North Hill", kindId: "sk3", label: { x: 680, y: 86, align: "top" } },
    { id: "s8", nodeId: "n9", name: "Inner West", kindId: "sk1", label: { x: 200, y: 196, align: "top" } },
    { id: "s9", nodeId: "n10", name: "Central", kindId: "sk2", label: { x: 320, y: 196, align: "top" } },
    { id: "s10", nodeId: "n11", name: "Market", kindId: "sk2", label: { x: 440, y: 196, align: "top" } },
    { id: "s11", nodeId: "n12", name: "East Gate", kindId: "sk3", label: { x: 560, y: 196, align: "top" } },
    { id: "s12", nodeId: "n13", name: "Docklands", kindId: "sk1", label: { x: 320, y: 366, align: "bottom" } },
    { id: "s13", nodeId: "n14", name: "Airport Spur", kindId: "sk3", label: { x: 440, y: 366, align: "bottom" } },
  ],
  segments: [
    { id: "sg1", sheetId: "sh1", fromNodeId: "n1", toNodeId: "n2", geometry: { kind: "straight" } },
    { id: "sg2", sheetId: "sh1", fromNodeId: "n2", toNodeId: "n3", geometry: { kind: "straight" } },
    { id: "sg3", sheetId: "sh1", fromNodeId: "n3", toNodeId: "n4", geometry: { kind: "straight" } },
    { id: "sg4", sheetId: "sh1", fromNodeId: "n2", toNodeId: "n5", geometry: { kind: "straight" } },
    { id: "sg5", sheetId: "sh1", fromNodeId: "n5", toNodeId: "n6", geometry: { kind: "straight" } },
    { id: "sg6", sheetId: "sh1", fromNodeId: "n3", toNodeId: "n7", geometry: { kind: "straight" } },
    { id: "sg7", sheetId: "sh1", fromNodeId: "n7", toNodeId: "n8", geometry: { kind: "straight" } },
    { id: "sg8", sheetId: "sh2", fromNodeId: "n9", toNodeId: "n10", geometry: { kind: "straight" } },
    { id: "sg9", sheetId: "sh2", fromNodeId: "n10", toNodeId: "n11", geometry: { kind: "straight" } },
    { id: "sg10", sheetId: "sh2", fromNodeId: "n11", toNodeId: "n12", geometry: { kind: "straight" } },
    { id: "sg11", sheetId: "sh2", fromNodeId: "n10", toNodeId: "n13", geometry: { kind: "straight" } },
    { id: "sg12", sheetId: "sh2", fromNodeId: "n13", toNodeId: "n14", geometry: { kind: "straight" } },
  ],
  lines: [
    { id: "l1", name: "C1", color: "#e11d48", strokeWidth: 10, strokeStyle: "solid" },
    { id: "l2", name: "C2", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" },
    { id: "l3", name: "C3", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" },
  ],
  lineRuns: [
    { id: "lr1", lineId: "l1", segmentIds: ["sg1", "sg2", "sg3"] },
    { id: "lr2", lineId: "l2", segmentIds: ["sg1", "sg2", "sg6", "sg7", "sg8", "sg9", "sg10"] },
    { id: "lr3", lineId: "l3", segmentIds: ["sg2", "sg4", "sg5", "sg9", "sg11", "sg12"] },
  ],
};

export const DEVELOPMENT_BOOTSTRAP_MAP: RailwayMap = {
  sheets: [
    { id: "sh-ov", name: "Regional Overview" },
    { id: "sh-mid", name: "Mid Distance" },
    { id: "sh-urban", name: "Urban Core" },
    { id: "sh-north", name: "Northern District" },
  ],
  nodes: [
    { id: "n-ov-1", sheetId: "sh-ov", x: 120, y: 260 },
    { id: "n-ov-2", sheetId: "sh-ov", x: 300, y: 260 },
    { id: "n-ov-3", sheetId: "sh-ov", x: 500, y: 260 },
    { id: "n-ov-4", sheetId: "sh-ov", x: 710, y: 260 },
    { id: "n-ov-5", sheetId: "sh-ov", x: 900, y: 260 },
    { id: "n-ov-6", sheetId: "sh-ov", x: 500, y: 120 },
    { id: "n-ov-7", sheetId: "sh-ov", x: 500, y: 400 },
    { id: "n-mid-1", sheetId: "sh-mid", x: 160, y: 220 },
    { id: "n-mid-2", sheetId: "sh-mid", x: 320, y: 220 },
    { id: "n-mid-3", sheetId: "sh-mid", x: 480, y: 220 },
    { id: "n-mid-4", sheetId: "sh-mid", x: 640, y: 220 },
    { id: "n-mid-5", sheetId: "sh-mid", x: 800, y: 220 },
    { id: "n-mid-6", sheetId: "sh-mid", x: 320, y: 360 },
    { id: "n-mid-7", sheetId: "sh-mid", x: 480, y: 360 },
    { id: "n-mid-8", sheetId: "sh-mid", x: 640, y: 360 },
    { id: "n-urban-1", sheetId: "sh-urban", x: 180, y: 220 },
    { id: "n-urban-2", sheetId: "sh-urban", x: 300, y: 220 },
    { id: "n-urban-3", sheetId: "sh-urban", x: 420, y: 220 },
    { id: "n-urban-4", sheetId: "sh-urban", x: 540, y: 220 },
    { id: "n-urban-5", sheetId: "sh-urban", x: 660, y: 220 },
    { id: "n-urban-6", sheetId: "sh-urban", x: 300, y: 340 },
    { id: "n-urban-7", sheetId: "sh-urban", x: 420, y: 340 },
    { id: "n-urban-8", sheetId: "sh-urban", x: 540, y: 340 },
    { id: "n-north-1", sheetId: "sh-north", x: 220, y: 180 },
    { id: "n-north-2", sheetId: "sh-north", x: 400, y: 180 },
    { id: "n-north-3", sheetId: "sh-north", x: 580, y: 180 },
    { id: "n-north-4", sheetId: "sh-north", x: 400, y: 320 },
  ],
  stationKinds: [
    { id: "sk-stop", name: "Stop", shape: "circle", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT },
    { id: "sk-hub", name: "Hub", shape: "interchange", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: "700" },
    { id: "sk-terminal", name: "Terminal", shape: "terminal", fontFamily: DEFAULT_STATION_FONT_FAMILY, fontWeight: DEFAULT_STATION_FONT_WEIGHT },
  ],
  stations: [
    { id: "s-ov-1", nodeId: "n-ov-1", name: "West Junction", kindId: "sk-terminal", label: { x: 106, y: 236, align: "top" } },
    { id: "s-ov-2", nodeId: "n-ov-2", name: "Lakeside", kindId: "sk-stop", label: { x: 286, y: 236, align: "top" } },
    { id: "s-ov-3", nodeId: "n-ov-3", name: "Central Exchange", kindId: "sk-hub", label: { x: 524, y: 224, align: "right" } },
    { id: "s-ov-4", nodeId: "n-ov-4", name: "Airport", kindId: "sk-terminal", label: { x: 734, y: 248, align: "right" } },
    { id: "s-ov-5", nodeId: "n-ov-5", name: "East Bay", kindId: "sk-terminal", label: { x: 924, y: 248, align: "right" } },
    { id: "s-ov-6", nodeId: "n-ov-6", name: "North Ridge", kindId: "sk-terminal", label: { x: 524, y: 108, align: "right" } },
    { id: "s-ov-7", nodeId: "n-ov-7", name: "South Harbor", kindId: "sk-terminal", label: { x: 524, y: 424, align: "right" } },
    { id: "s-mid-1", nodeId: "n-mid-1", name: "Elm", kindId: "sk-stop", label: { x: 160, y: 196, align: "top" } },
    { id: "s-mid-2", nodeId: "n-mid-2", name: "Market West", kindId: "sk-stop", label: { x: 320, y: 196, align: "top" } },
    { id: "s-mid-3", nodeId: "n-mid-3", name: "Grand Square", kindId: "sk-hub", label: { x: 504, y: 214, align: "right" } },
    { id: "s-mid-4", nodeId: "n-mid-4", name: "University", kindId: "sk-stop", label: { x: 664, y: 214, align: "right" } },
    { id: "s-mid-5", nodeId: "n-mid-5", name: "East Works", kindId: "sk-terminal", label: { x: 824, y: 214, align: "right" } },
    { id: "s-mid-6", nodeId: "n-mid-6", name: "Canal", kindId: "sk-stop", label: { x: 320, y: 386, align: "bottom" } },
    { id: "s-mid-7", nodeId: "n-mid-7", name: "Civic", kindId: "sk-stop", label: { x: 504, y: 350, align: "right" } },
    { id: "s-mid-8", nodeId: "n-mid-8", name: "South Park", kindId: "sk-terminal", label: { x: 664, y: 386, align: "bottom" } },
    { id: "s-urban-1", nodeId: "n-urban-1", name: "West End", kindId: "sk-stop", label: { x: 180, y: 196, align: "top" } },
    { id: "s-urban-2", nodeId: "n-urban-2", name: "Museum", kindId: "sk-stop", label: { x: 300, y: 196, align: "top" } },
    { id: "s-urban-3", nodeId: "n-urban-3", name: "Central", kindId: "sk-hub", label: { x: 444, y: 214, align: "right" } },
    { id: "s-urban-4", nodeId: "n-urban-4", name: "Riverfront", kindId: "sk-stop", label: { x: 564, y: 214, align: "right" } },
    { id: "s-urban-5", nodeId: "n-urban-5", name: "East Gate", kindId: "sk-terminal", label: { x: 684, y: 214, align: "right" } },
    { id: "s-urban-6", nodeId: "n-urban-6", name: "Old Town", kindId: "sk-stop", label: { x: 324, y: 364, align: "bottom" } },
    { id: "s-urban-7", nodeId: "n-urban-7", name: "Civic Center", kindId: "sk-hub", label: { x: 444, y: 364, align: "bottom" } },
    { id: "s-urban-8", nodeId: "n-urban-8", name: "Harbor Line", kindId: "sk-stop", label: { x: 564, y: 364, align: "bottom" } },
    { id: "s-north-1", nodeId: "n-north-1", name: "Pine", kindId: "sk-stop", label: { x: 220, y: 156, align: "top" } },
    { id: "s-north-2", nodeId: "n-north-2", name: "North Central", kindId: "sk-hub", label: { x: 424, y: 174, align: "right" } },
    { id: "s-north-3", nodeId: "n-north-3", name: "Summit", kindId: "sk-terminal", label: { x: 604, y: 174, align: "right" } },
    { id: "s-north-4", nodeId: "n-north-4", name: "Valley", kindId: "sk-stop", label: { x: 424, y: 344, align: "right" } },
  ],
  segments: [
    { id: "sg-ov-1", sheetId: "sh-ov", fromNodeId: "n-ov-1", toNodeId: "n-ov-2", geometry: { kind: "straight" } },
    { id: "sg-ov-2", sheetId: "sh-ov", fromNodeId: "n-ov-2", toNodeId: "n-ov-3", geometry: { kind: "straight" } },
    { id: "sg-ov-3", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-4", geometry: { kind: "straight" } },
    { id: "sg-ov-4", sheetId: "sh-ov", fromNodeId: "n-ov-4", toNodeId: "n-ov-5", geometry: { kind: "straight" } },
    { id: "sg-ov-5", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-6", geometry: { kind: "straight" } },
    { id: "sg-ov-6", sheetId: "sh-ov", fromNodeId: "n-ov-3", toNodeId: "n-ov-7", geometry: { kind: "straight" } },
    { id: "sg-mid-1", sheetId: "sh-mid", fromNodeId: "n-mid-1", toNodeId: "n-mid-2", geometry: { kind: "straight" } },
    { id: "sg-mid-2", sheetId: "sh-mid", fromNodeId: "n-mid-2", toNodeId: "n-mid-3", geometry: { kind: "straight" } },
    { id: "sg-mid-3", sheetId: "sh-mid", fromNodeId: "n-mid-3", toNodeId: "n-mid-4", geometry: { kind: "straight" } },
    { id: "sg-mid-4", sheetId: "sh-mid", fromNodeId: "n-mid-4", toNodeId: "n-mid-5", geometry: { kind: "straight" } },
    { id: "sg-mid-5", sheetId: "sh-mid", fromNodeId: "n-mid-2", toNodeId: "n-mid-6", geometry: { kind: "straight" } },
    { id: "sg-mid-6", sheetId: "sh-mid", fromNodeId: "n-mid-6", toNodeId: "n-mid-7", geometry: { kind: "straight" } },
    { id: "sg-mid-7", sheetId: "sh-mid", fromNodeId: "n-mid-7", toNodeId: "n-mid-8", geometry: { kind: "straight" } },
    { id: "sg-mid-8", sheetId: "sh-mid", fromNodeId: "n-mid-3", toNodeId: "n-mid-7", geometry: { kind: "straight" } },
    { id: "sg-urban-1", sheetId: "sh-urban", fromNodeId: "n-urban-1", toNodeId: "n-urban-2", geometry: { kind: "straight" } },
    { id: "sg-urban-2", sheetId: "sh-urban", fromNodeId: "n-urban-2", toNodeId: "n-urban-3", geometry: { kind: "straight" } },
    { id: "sg-urban-3", sheetId: "sh-urban", fromNodeId: "n-urban-3", toNodeId: "n-urban-4", geometry: { kind: "straight" } },
    { id: "sg-urban-4", sheetId: "sh-urban", fromNodeId: "n-urban-4", toNodeId: "n-urban-5", geometry: { kind: "straight" } },
    { id: "sg-urban-5", sheetId: "sh-urban", fromNodeId: "n-urban-2", toNodeId: "n-urban-6", geometry: { kind: "straight" } },
    { id: "sg-urban-6", sheetId: "sh-urban", fromNodeId: "n-urban-6", toNodeId: "n-urban-7", geometry: { kind: "straight" } },
    { id: "sg-urban-7", sheetId: "sh-urban", fromNodeId: "n-urban-7", toNodeId: "n-urban-8", geometry: { kind: "straight" } },
    { id: "sg-urban-8", sheetId: "sh-urban", fromNodeId: "n-urban-3", toNodeId: "n-urban-7", geometry: { kind: "straight" } },
    { id: "sg-urban-9", sheetId: "sh-urban", fromNodeId: "n-urban-4", toNodeId: "n-urban-8", geometry: { kind: "straight" } },
    { id: "sg-north-1", sheetId: "sh-north", fromNodeId: "n-north-1", toNodeId: "n-north-2", geometry: { kind: "straight" } },
    { id: "sg-north-2", sheetId: "sh-north", fromNodeId: "n-north-2", toNodeId: "n-north-3", geometry: { kind: "straight" } },
    { id: "sg-north-3", sheetId: "sh-north", fromNodeId: "n-north-2", toNodeId: "n-north-4", geometry: { kind: "straight" } },
  ],
  lines: [
    { id: "l-red", name: "Red", color: "#dc2626", strokeWidth: 10, strokeStyle: "solid" },
    { id: "l-blue", name: "Blue", color: "#2563eb", strokeWidth: 10, strokeStyle: "dashed" },
    { id: "l-green", name: "Green", color: "#16a34a", strokeWidth: 10, strokeStyle: "solid" },
    { id: "l-gold", name: "Gold", color: "#d97706", strokeWidth: 8, strokeStyle: "dotted" },
    { id: "l-teal", name: "Teal", color: "#0f766e", strokeWidth: 12, strokeStyle: "solid" },
  ],
  lineRuns: [
    { id: "lr-red", lineId: "l-red", segmentIds: ["sg-ov-1", "sg-ov-2", "sg-ov-3", "sg-ov-4", "sg-mid-1", "sg-mid-2", "sg-mid-3", "sg-mid-4", "sg-urban-1", "sg-urban-2", "sg-urban-3", "sg-urban-4"] },
    { id: "lr-blue", lineId: "l-blue", segmentIds: ["sg-ov-2", "sg-ov-5", "sg-mid-2", "sg-mid-8", "sg-urban-2", "sg-urban-8", "sg-north-1", "sg-north-2"] },
    { id: "lr-green", lineId: "l-green", segmentIds: ["sg-ov-2", "sg-ov-6", "sg-mid-5", "sg-mid-6", "sg-mid-7", "sg-urban-5", "sg-urban-6", "sg-urban-7"] },
    { id: "lr-gold", lineId: "l-gold", segmentIds: ["sg-mid-3", "sg-mid-4", "sg-north-3"] },
    { id: "lr-teal", lineId: "l-teal", segmentIds: ["sg-urban-3", "sg-urban-9"] },
  ],
};
